baseurl: /
gems: [jekyll-paginate]
paginate: 7
paginate_path: "page:num"
encoding: utf-8
markdown: kramdown
kramdown:
    input: GFM
# 作者信息
author: 
  github: http://github.com/octobug
  weibo: http://weibo.com/qq362499939
  wooyun: http://www.wooyun.org/whitehats/bitemebitch
  qzone: http://user.qzone.qq.com/362499939
  weixin: images/weixin_qrcode.png

#markdown: redcarpet
#permalink: /404.html
port: 6582
